"""
Pydantic data models for Grounded Answer Generation with Gemini.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from backend.app.models.retrieval import RetrievedChunk


class GenerateRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="The user's financial question to answer using grounded knowledge documents.",
        examples=["Under RBI guidelines, how often must high-risk customer KYC be updated?"],
    )
    enable_rerank: bool = Field(
        default=True,
        description="Whether to apply NVIDIA cross-encoder reranking to initial vector candidates before generation.",
    )
    top_k: Optional[int] = Field(
        default=None,
        description="Number of candidate chunks to retrieve from vector search (default 15).",
        ge=1,
        le=50,
    )
    top_n: Optional[int] = Field(
        default=None,
        description="Number of final chunks to provide as context to Gemini (default 5).",
        ge=1,
        le=15,
    )
    temperature: Optional[float] = Field(
        default=None,
        description="Sampling temperature for Gemini (0.0 to 1.0, default 0.1 for high factual grounding).",
        ge=0.0,
        le=1.0,
    )

    @field_validator("question", mode="before")
    @classmethod
    def clean_question(cls, v: Any) -> str:
        if not isinstance(v, str):
            raise ValueError("Question must be a string.")
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("Question cannot be empty or whitespace only.")
        return trimmed


class SourceCitation(BaseModel):
    source_id: int = Field(..., description="1-based citation identifier corresponding to [Source N].")
    chunk_id: str = Field(..., description="Unique ID of the cited chunk.")
    document_name: str = Field(..., description="Title or name of the cited bank document.")
    source_dataset: str = Field(..., description="Origin of document: 'rbi' or 'indian_finance'.")
    section: Optional[str] = Field(default=None, description="Document section or subtopic.")
    similarity: float = Field(..., description="Vector cosine similarity.")
    rerank_score: Optional[float] = Field(default=None, description="NVIDIA Reranker probability score.")
    initial_rank: Optional[int] = Field(default=None, description="Original rank before reranking.")


class GenerateResponse(BaseModel):
    question: str = Field(..., description="The queried question.")
    answer: str = Field(..., description="Grounded answer generated by Gemini with inline citations.")
    is_grounded: bool = Field(default=True, description="Whether the answer is grounded in retrieved documents.")
    is_insufficient_context: bool = Field(
        default=False,
        description="True if the retrieved documents did not contain sufficient facts to answer the question.",
    )
    sources: List[RetrievedChunk] = Field(
        default_factory=list,
        description="Ordered list of retrieved chunks supplied as context.",
    )
    cited_source_ids: List[int] = Field(
        default_factory=list,
        description="List of 1-based source IDs cited in the answer (e.g. [1, 2]).",
    )
    model: str = Field(..., description="Gemini model identifier used for generation.")
    total_candidates: int = Field(default=0, description="Total vector candidates evaluated.")
    reranked: bool = Field(default=False, description="Whether NVIDIA reranking was applied.")
